version: '3'

services:
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - ./maria:/etc/mysql/
    env_file:
      - mariadb.env
  django:
    image: pttweb:0.0.0
    restart: always
    ports:
      - 9898:8888
    env_file:
      - pttweb.env
    volumes:
      - ./static_pttweb:/app/static_pttweb
    depends_on:
    - mariadb
